import React, { useEffect, useState } from "react";
import Head from "next/head";
import LandingSection from "../src/components/LandingSection";
import BoysHome from "../src/components/BoysHome";
import GirlsHome from "../src/components/GirlsHome";
import Footer from "../src/components/Footer";
export default function Home() {
  

  return (
    <div className="">
      <Head>
        <title>Ak-Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingSection />
      <BoysHome />
      <GirlsHome />
    </div>
  );
}
